const {Schema,model, SchemaType}= require("mongoose");
const freelancer_schema= new Schema({
    firstName:{
        type:String,
        required:true
    },
    lastName:{
        type:String,
        required:true
    },
    userName:{
        type:String,
        required:true
    },
    password:{
        type:String,
        required:true  
    },
    Email:{
        type:String,
        required:true
    },
    phone:{
        type:String,
        required:true  
    },
    Dob:{
        type:String,
        required:true
    },
    professionalInfo:{
        type:Schema.Types.Mixed,
        required:true
    },
    Skills:{
        type:String,
        required:true
    },
    Education:{
        type:Schema.Types.Mixed,
        required:true
    },
    Role:{
        type:String,
        required:true
    },
    project:[{
        type:Schema.Types.ObjectId,
        ref:"Project"
    }],
    Refer:{
        type:String,
        required:true
    },
    verified:{
        type:Schema.Types.Mixed
    },
    isVerified:{
        type:Boolean
    },
    githubLink:{
        type:String
    },
    Linkdin:{
        type:String
    },
    personalWebsite:{
        type:String
    },
    perHourPrice:{
Type:Number,
required:True
    },
    connects:{
        type:Number,
        default:0
    },
    Resume:{
        type:Buffer
    },
    InterviewedBy:{
        type:String
    },
    workExperience:{
        type:String,
        required:true
    },
    isfreelancer:{
        required:true,
        default:"True"
    }
},{timestamps:true});

const freelancer_project= new Schema({
projectName:{
    type:String,
        required:true
},
Description:{
    type:String,
    required:true
},
verified:{
    type:Schema.Types.Mixed
},
isVerified:{
    type:String
},
githubLink:{
    type:String,
    required:true
},
Start:{
    type:Date
},
End:{
    type:Date
},
Refer:{
    type:String,
    required:true
},
TechUsed:[{
    type:String,
    required:true
}],
Role:{
    type:String,
    required:true
},
projectType:{
    type:String,
    required:true
}

},{timestamps:true});
const otpSchema= new Schema({
    email:{
        required:true,
        type:String
    },
    phone:{
        required:true,
        type:Number
    },
    otp:{
        required:true,
        type:String 
    }
});






const businessSchema= new Schema({
    firstName:{
        type:String,
        required:true
    },
    lastName:{
        type:String,
        required:true
    },
    companyName:{
        type:String,
        required:true
    },
    companySize:{
        type:String,
        required:true
    },
    password:{
        type:String,
        required:true  
    },
    Email:{
        type:String,
        required:true
    },
    phone:{
        type:String,
        required:true  
    },
    Dob:{
        type:String,
        required:true
    },
    Position:{
        type:String,
        required:true
    },
    Refer:{
        type:String,
        required:true
    },
    verified:{
        type:Schema.Types.Mixed
    },
    isVerified:{
        type:Boolean
    },
    Linkdin:{
        type:String
    },
    personalWebsite:{
        type:String
    },
    isBusiness:{
        required:true,
        default:"True"
    },
    connects:{
        type:Number,
        default:0
    }
})
const otp= new model("user_otp",otpSchema)
 const Freelancer= new model("freelancer_data",freelancer_schema);
 const project= new model("Project",freelancer_project)
 const Business= new model("Business_Data",businessSchema)
  module.exports= {Freelancer,project,otp,Business};