import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/Pagecomponents/Navbar";
import { Authprovider } from "@/context/context";
const inter = Inter({ subsets: ["latin"] });


export const metadata = {
  title: "Dehix",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
       
<Authprovider>
<Navbar />
        <div className="pt-16">
          {children}
        </div>
</Authprovider>
      </body>
    </html>
  );
}
